---
# - name: Set up cluster-wide configuration.
#   hosts: k3s_cluster
#   become: true

#   tasks: []

- name: Deploy Kubernetes resources via master node.
  hosts: master
  gather_facts: false

  collections:
    - kubernetes.core

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: ~/.kube/config
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  roles:
    - role: setup
      tags: ['setup']

    - role: cluster_monitoring
      tags: ['monitoring', 'prometheus']

    - role: drupal
      tags: ['drupal']

    - role: wordpress
      tags: ['wordpress']

    - role: minecraft
      tags: ['minecraft']

    - role: pihole
      tags: ['pihole']

    - role: status
      tags: ['status', 'debug']
